## Importar o CSV

In [3]:
import pandas as pd

cols = ['NU_INSCRICAO', 'IN_TREINEIRO', 'TP_SEXO', 'TP_FAIXA_ETARIA',
        'TP_COR_RACA', 'TP_ESTADO_CIVIL', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU',
        'TP_ENSINO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA',
        'CO_UF_PROVA', 'SG_UF_PROVA', 'Q001', 'Q002', 'Q003', 'Q004',
        'Q005', 'Q006','Q007','Q020', 'Q023']

cols_presenca = ['NU_SEQUENCIAL', 'NO_MUNICIPIO_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 
                 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT']

#Gabriel, se estiver muito pesado, deixa comentário esse item
cols_desempenho = ['TP_ESCOLA', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']


df = pd.read_csv(
    'C:/Users/V/downloads/Desigualdade_Demografica_ENEM-main/microdados_enem_2025/DADOS/PARTICIPANTES_2025.csv',
    sep=';',
    encoding='ISO-8859-1',
    usecols=cols
)
#Se estiver pesado também, pode deixar comentário, mas alguns dados essenciais utilizei esse.
df_resultados = pd.read_csv(
    'C:/Users/V/Downloads/microdados_enem_2025/DADOS/RESULTADOS_2025.csv',
    sep=';',
    encoding='ISO-8859-1',
    usecols=cols_presenca
)


#Esse pdf.read como comentário
df_2019 = pd.read_csv(
    'C:/Users/V/downloads/microdados_enem_2019/DADOS/MICRODADOS_ENEM_2019.csv',
    sep=';',
    encoding='ISO-8859-1',
    usecols=cols_desempenho
)
#Esse pdf.read como comentário
df_2020 = pd.read_csv(
    'C:/Users/V/downloads/microdados_enem_2020/DADOS/MICRODADOS_ENEM_2020.csv',
    sep=';',
    encoding='ISO-8859-1',
    usecols=cols_desempenho
)
#Não finalizei o tópico dois ainda (Verificar a discrepância das notas ao longos dos anos 2020 a 2022),
#São arquivos muitos pesados e já fica fora de cogitação carregar tantos arquivos p esados

In [4]:
df

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,...,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q020,Q023
0,210066506229,6,F,1,2,1,4,NaN,0,2932200,...,BA,C,F,A,A,1,B,B,A,A
1,210066506230,3,M,1,1,2,0,1.0,0,2910800,...,BA,B,E,C,B,3,A,D,B,A
2,210066506231,2,F,1,1,3,0,NaN,1,3549805,...,SP,E,E,D,D,6,A,F,B,C
3,210066506232,2,M,1,3,2,0,1.0,0,2203909,...,PI,D,F,D,D,3,A,B,B,D
4,210066506233,1,F,1,1,3,0,NaN,1,5101803,...,MT,G,G,E,E,4,B,Q,B,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4810767,210071444509,12,F,1,1,1,14,NaN,0,2611606,...,PE,G,G,E,E,7,B,I,B,D
4810768,210071444513,4,M,1,1,1,1,NaN,0,3522208,...,SP,F,E,D,B,4,A,C,B,E
4810769,210071444514,11,M,1,1,1,10,NaN,0,3505708,...,SP,E,E,F,F,4,B,I,B,A
4810770,210071444515,8,F,1,2,1,5,NaN,0,3509502,...,SP,E,E,F,F,1,B,C,B,A
4810771,210071444516,13,F,2,3,1,14,NaN,0,3168606,...,MG,D,D,B,B,5,B,C,B,A

---

## Filtrar para trocar os Nulos e Treineiros

In [5]:
df['IN_TREINEIRO'].value_counts() #Saber quantos tem
df = df[df['IN_TREINEIRO'] == 0].copy() #Filtra só para não ter treineiros

In [6]:
df.isnull().sum().sort_values(ascending=False) #Ver os nulos por coluna do maior ao menor
#Somento o TP_ENSINO ta(tava) com 2092958 valores nulos

TP_ENSINO             2092958
NU_INSCRICAO                0
TP_SEXO                     0
TP_ESTADO_CIVIL             0
TP_COR_RACA                 0
TP_FAIXA_ETARIA             0
TP_ST_CONCLUSAO             0
TP_ANO_CONCLUIU             0
IN_TREINEIRO                0
CO_MUNICIPIO_PROVA          0
NO_MUNICIPIO_PROVA          0
CO_UF_PROVA                 0
SG_UF_PROVA                 0
Q001                        0
Q002                        0
Q003                        0
Q004                        0
Q005                        0
Q006                        0
Q007                        0
Q020                        0
Q023                        0
dtype: int64

In [7]:
#Colunas de identifição e localização
cols_essenciais = ['CO_MUNICIPIO_PROVA', "SG_UF_PROVA", "TP_SEXO"]
df = df.dropna(subset=cols_essenciais)

#Colunas de questionario socioeconomico
cols_questionario = ['Q001', "Q002", "Q003", "Q004", "Q005", "Q006", "Q007"]
for col in cols_questionario:
    df[col] = df[col].fillna("NÃO INFORMADO")

#Categorias das caracteristicas do candiadato
cols_tp = ['TP_COR_RACA', 'TP_ESTADO_CIVIL', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ENSINO']
for col in cols_tp:
    df[col] = df[col].fillna('NÃO INFORMADO')

# Colunas de identificação e localização dos resultados
cols_identificacao_resultados = ['NU_SEQUENCIAL', 'NO_MUNICIPIO_PROVA', 'SG_UF_PROVA']

# Colunas de presença nos dias de prova
cols_presenca = ['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT']

# Colunas de desempenho nas áreas do conhecimento
cols_desempenho = ['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']

---

## Participação por município/UF

In [8]:
part_municipio = (
    df.groupby(["NO_MUNICIPIO_PROVA", "SG_UF_PROVA"]).size()
    .reset_index(name='qtd_participantes')
    .sort_values('qtd_participantes' , ascending=False)
)

part_municipio.head(10)

     NO_MUNICIPIO_PROVA SG_UF_PROVA  qtd_participantes
1610          São Paulo          SP             160867
1383     Rio de Janeiro          RJ             110561
1404           Salvador          BA              72167
260            Brasília          DF              67665
603           Fortaleza          CE              65840
212      Belo Horizonte          MG              59170
949              Manaus          AM              57916
215               Belém          PA              56554
1593           São Luís          MA              45548
1345             Recife          PE              42009

In [9]:
"""
Pensando em inisght pra cá, talvez junte com o Urbano X Rural para enriquecer mais aqui
"""
part_municipio.tail(10)

       NO_MUNICIPIO_PROVA SG_UF_PROVA  qtd_participantes
1715             Uiramutã          RR                104
392              Carlinda          MT                101
95               Araguanã          TO                101
184        Barra do Turvo          SP                 99
1147            Pacaraima          RR                 89
264    Brejinho de Nazaré          TO                 70
51                Amajari          RR                 53
1440  Santa Rosa do Purus          AC                 48
588   Fernando de Noronha          PE                 44
587       Fernando Falcão          MA                 32

In [10]:
part_uf = df["SG_UF_PROVA"].value_counts().reset_index()
part_uf.columns = ["UF", "qtd_participantes"]

part_uf.head(5)

   UF  qtd_participantes
0  SP             603948
1  MG             368958
2  BA             342861
3  RJ             275221
4  PA             228700

In [11]:
part_uf.tail(5)

    UF  qtd_participantes
22  RO              38576
23  TO              27323
24  AP              27263
25  AC              24447
26  RR              11212

In [12]:
#Grafico com matplos

---

## O Recorte Racial

In [13]:
# Ta como numeros os valores, vou trocar para valores que estão relacionados baseado no dicionario (lembrar de fazer isso nas outras que tiver) pra melhorar a leitura
df['TP_COR_RACA'].value_counts()

TP_COR_RACA
3    1731462
1    1443406
2     518900
4      52684
0      44603
5      32067
Name: count, dtype: int64

In [14]:
#Mapear os valores
mapa_cor_raca = {
    0:'Não Declarado',
    1:'Branco',
    2:'Preta',
    3:'Parda',
    4:'Amarela',
    5:'Indigena'
}

#colocar o mapeamento na coluna, atribuimos a outra coluna nova
df['cor_raca'] = df['TP_COR_RACA'].map(mapa_cor_raca)

#Verificando
df['cor_raca'].value_counts()

cor_raca
Parda            1731462
Branco           1443406
Preta             518900
Amarela            52684
Não Declarado      44603
Indigena           32067
Name: count, dtype: int64

In [15]:
# Agora analisar o tipo de escola
df['Q023'].value_counts()

Q023
A    3086940
D     405622
B     136894
E     113909
C      68011
F      11746
Name: count, dtype: int64

In [16]:
# A coluna Q023 (Em que tipo de escola você frequentou ou frequenta o Ensino Médio?) está com mesma formatação da anterior (que eu lembre de limpar todas)
mapa_tipo_escola = {
    'A': 'Só pública',
    'B': 'Pública + privada (sem bolsa)',
    'C': 'Pública + privada (com bolsa)',
    'D': 'Só privada (sem bolsa)',
    'E': 'Só privada (com bolsa)',
    'F': 'Não frequentou Ensino Médio'
}

#mapear ela em nova coluna
df['tipo_escola'] = df["Q023"].map(mapa_tipo_escola)

#Verificando
df['tipo_escola'].value_counts()

tipo_escola
Só pública                       3086940
Só privada (sem bolsa)            405622
Pública + privada (sem bolsa)     136894
Só privada (com bolsa)            113909
Pública + privada (com bolsa)      68011
Não frequentou Ensino Médio        11746
Name: count, dtype: int64

In [17]:
#Agora cruzar as duas colunas para tirar boas conclusões
tabela_raca_escola = pd.crosstab(df['cor_raca'], df['tipo_escola'], normalize='index') * 100
tabela_raca_escola.round(1)

tipo_escola,Não frequentou Ensino Médio,Pública + privada (com bolsa),Pública + privada (sem bolsa),Só privada (com bolsa),Só privada (sem bolsa),Só pública
cor_raca,,,,,,
Amarela,0.3,1.7,3.8,3.1,12.9,78.2
Branco,0.3,2.0,4.4,4.3,18.8,70.2
Indigena,0.3,1.1,2.0,0.9,1.6,94.0
Não Declarado,0.6,1.7,4.2,2.7,10.7,80.1
Parda,0.3,1.6,3.1,2.1,5.8,87.0
Preta,0.3,1.9,2.9,2.2,4.2,88.5

A raça indígena apresenta a maior concentração em escolas exclusivamente públicas (94,0%) e a menor presença em escolas privadas com bolsa integral (0,9%), indicando menor acesso à rede privada em comparação às demais categorias.

Cabe notar que a categoria Indígena representa uma fração pequena da amostra total (n = 32.067), o que deve ser considerado na interpretação da magnitude do resultado

In [18]:
#Fazer grafico com matplot

---

## Candidato Possui internet?
 (Acho que falta algo a mais, pedir ideia pro professor e pro vinicius de coisas que posso botar)

In [19]:
"""
De acordo com o Dicionario do enem (arquivo esse na pasta /Dicionario/Dicionário_Microdados_Enem_2025.xlsx)
A - Não
B - Sim

Vou mapear para ajustar melhor o resultado

87,62% dos candidatos possuem internet
12,37% não possuem
"""

mapa_internet = {
    'A':'Não',
    'B':'Sim'
}

df['tem_internet'] = df['Q020'].map(mapa_internet)

df['tem_internet'].value_counts(normalize=True) * 100

tem_internet
Sim    87.626709
Não    12.373291
Name: proportion, dtype: float64

In [20]:
#Vamos separar por estado

"""
É notado uma grande deficiencia com internet na nossa nação, observando na tabela onde o estado
do Amazonas , os candidatos que possuem não internet ocupam 31.22% do total de inscritos, isso sem
incluir treineiros.
"""

tabela_internet_uf = pd.crosstab(df['SG_UF_PROVA'], df['tem_internet'], normalize='index') * 100
tabela_internet_uf.round(2).sort_values('Não', ascending=False)

tem_internet    Não    Sim
SG_UF_PROVA
AM            31.22  68.78
PA            27.04  72.96
AC            27.03  72.97
MA            23.11  76.89
AP            21.90  78.10
PI            18.30  81.70
SE            17.75  82.25
CE            16.55  83.45
TO            16.03  83.97
BA            15.47  84.53
RR            15.04  84.96
AL            14.78  85.22
PB            13.75  86.25
PE            11.54  88.46
RJ            11.46  88.54
RN            10.66  89.34
MT            10.39  89.61
RO             9.80  90.20
GO             9.71  90.29
MS             8.50  91.50
DF             8.22  91.78
MG             7.84  92.16
ES             6.50  93.50
RS             5.56  94.44
SP             5.53  94.47
PR             4.63  95.37
SC             4.19  95.81

### Renda Familiar x Acesso à Internet

In [21]:
#Gabriel, para adicionar mais informações com acesso a rede, adicionei Renda Familiar x Acesso à internet pra complementar, 
# queria sua opnião depois sobre esse assunto, 

# Mapear as faixas de renda familiar dos candidatos
mapa_renda = {
    'A': 'Nenhuma renda',
    'B': 'Até R$ 1.518,00',
    'C': 'R$ 1.518,01 a R$ 2.277,00',
    'D': 'R$ 2.277,01 a R$ 3.036,00',
    'E': 'R$ 3.036,01 a R$ 3.795,00',
    'F': 'R$ 3.795,01 a R$ 4.554,00',
    'G': 'R$ 4.554,01 a R$ 6.072,00',
    'H': 'R$ 6.072,01 a R$ 7.590,00',
    'I': 'R$ 7.590,01 a R$ 9.108,00',
    'J': 'R$ 9.108,01 a R$ 10.626,00',
    'K': 'R$ 10.626,01 a R$ 12.144,00',
    'L': 'R$ 12.144,01 a R$ 13.662,00',
    'M': 'R$ 13.662,01 a R$ 15.180,00',
    'N': 'R$ 15.180,01 a R$ 18.216,00',
    'O': 'R$ 18.216,01 a R$ 22.770,00',
    'P': 'R$ 22.770,01 a R$ 30.360,00',
    'Q': 'Acima de R$ 30.360,00'
}

df['renda_familiar'] = df['Q007'].map(mapa_renda)

ordem_renda = list(mapa_renda.values())

In [22]:
# Comparar o acesso à internet entre as diferentes faixas de renda
tabela_renda_internet = (
    pd.crosstab(
        df['renda_familiar'],
        df['tem_internet'],
        normalize='index'
    ) * 100
).round(1)

tabela_renda_internet = tabela_renda_internet.reindex(ordem_renda)

tabela_renda_internet

tem_internet                  Não   Sim
renda_familiar
Nenhuma renda                35.5  64.5
Até R$ 1.518,00              18.9  81.1
R$ 1.518,01 a R$ 2.277,00     7.1  92.9
R$ 2.277,01 a R$ 3.036,00     3.6  96.4
R$ 3.036,01 a R$ 3.795,00     2.5  97.5
R$ 3.795,01 a R$ 4.554,00     1.7  98.3
R$ 4.554,01 a R$ 6.072,00     1.1  98.9
R$ 6.072,01 a R$ 7.590,00     0.8  99.2
R$ 7.590,01 a R$ 9.108,00     0.5  99.5
R$ 9.108,01 a R$ 10.626,00    0.4  99.6
R$ 10.626,01 a R$ 12.144,00   0.4  99.6
R$ 12.144,01 a R$ 13.662,00   0.4  99.6
R$ 13.662,01 a R$ 15.180,00   0.3  99.7
R$ 15.180,01 a R$ 18.216,00   0.2  99.8
R$ 18.216,01 a R$ 22.770,00   0.2  99.8
R$ 22.770,01 a R$ 30.360,00   0.2  99.8
Acima de R$ 30.360,00         0.3  99.7

A relação entre renda familiar e acesso à internet mostra uma diferença mais evidente entre os candidatos de menor renda. Entre aqueles que declararam não possuir renda familiar, 3,6% não possuem acesso à internet, sendo o maior percentual observado entre as faixas analisadas.

Na faixa de renda de até R$ 1.518,00, 1,9% não possuem acesso à internet. Esse percentual diminui conforme a renda familiar aumenta, chegando a 0,7% entre os candidatos com renda de R$ 1.518,01 a R$ 2.277,00 e a valores próximos de zero nas faixas de renda mais altas.

---

## **Escolaridade dos pais x tipo de escola do filho**

In [23]:
#separar o mapa aqui pra deixar logo pro Q001 e Q002 por serem mesmas categorias
mapa_responsaveis = {
    'A': 'Nunca estudou',
    'B': 'Fund. incompleto (até 4ª/5º)',
    'C': 'Fund. incompleto (até 8ª/9º)',
    'D': 'Fund. completo',
    'E': 'Médio completo',
    'F': 'Superior completo',
    'G': 'Pós-graduação',
    'H': 'Não sei'
}

In [24]:
#Ate que serie seu pai/homem responsável estudou

df['escolaridade_pai'] = df['Q001'].map(mapa_responsaveis)

df['escolaridade_pai'].value_counts()

escolaridade_pai
Médio completo                  1055981
Fund. incompleto (até 4ª/5º)     651283
Fund. completo                   510593
Não sei                          489499
Fund. incompleto (até 8ª/9º)     450096
Superior completo                277304
Pós-graduação                    202126
Nunca estudou                    186240
Name: count, dtype: int64

In [25]:
#Ate que serie sua mãe/mulher responsável estudou

df['escolaridade_mae'] = df['Q002'].map(mapa_responsaveis)

df['escolaridade_mae'].value_counts()

escolaridade_mae
Médio completo                  1344927
Fund. completo                   561125
Fund. incompleto (até 4ª/5º)     469676
Superior completo                387656
Fund. incompleto (até 8ª/9º)     383991
Pós-graduação                    367053
Não sei                          187107
Nunca estudou                    121587
Name: count, dtype: int64

In [26]:
df['tipo_escola'].value_counts()

tipo_escola
Só pública                       3086940
Só privada (sem bolsa)            405622
Pública + privada (sem bolsa)     136894
Só privada (com bolsa)            113909
Pública + privada (com bolsa)      68011
Não frequentou Ensino Médio        11746
Name: count, dtype: int64

In [27]:
#escolaridade do pai x tipo de escola
pai_tipo = (pd.crosstab(df['escolaridade_pai'], df['tipo_escola'], normalize='index') * 100).round(1)
pai_tipo.sort_values(['Só privada (sem bolsa)', 'Só pública'], ascending=[False,True] )

tipo_escola,Não frequentou Ensino Médio,Pública + privada (com bolsa),Pública + privada (sem bolsa),Só privada (com bolsa),Só privada (sem bolsa),Só pública
escolaridade_pai,,,,,,
Pós-graduação,0.2,1.9,5.9,7.1,49.9,35.1
Superior completo,0.2,2.4,6.2,7.3,36.8,47.1
Médio completo,0.2,2.3,4.7,4.2,12.0,76.7
Fund. completo,0.2,1.9,3.2,2.4,5.5,86.9
Não sei,0.5,1.4,2.9,1.6,4.0,89.6
Fund. incompleto (até 8ª/9º),0.3,1.5,2.8,1.7,3.6,90.1
Fund. incompleto (até 4ª/5º),0.4,1.2,2.0,1.0,1.7,93.8
Nunca estudou,0.8,1.0,1.5,0.7,0.9,95.2

In [28]:
#escolaridade da mãe x tipo de escola
mae_tipo = (pd.crosstab(df['escolaridade_mae'], df['tipo_escola'], normalize='index') * 100).round(1)
mae_tipo.sort_values(['Só privada (sem bolsa)', 'Só pública'], ascending=[False,True] )

tipo_escola,Não frequentou Ensino Médio,Pública + privada (com bolsa),Pública + privada (sem bolsa),Só privada (com bolsa),Só privada (sem bolsa),Só pública
escolaridade_mae,,,,,,
Pós-graduação,0.1,2.3,5.8,7.0,36.8,48.0
Superior completo,0.2,2.7,5.7,6.7,29.2,55.5
Médio completo,0.2,2.1,4.1,3.3,8.8,81.6
Não sei,0.7,1.1,2.8,1.1,3.7,90.7
Fund. completo,0.3,1.4,2.6,1.5,3.3,90.9
Fund. incompleto (até 8ª/9º),0.4,1.2,2.2,1.1,2.2,93.0
Fund. incompleto (até 4ª/5º),0.5,1.1,1.8,0.7,1.1,94.9
Nunca estudou,1.2,1.0,1.6,0.6,0.8,94.9

na geração dos pais desses candidatos, homem com curso superior tende a ganhar mais que mulher com o mesmo curso (desigualdade salarial de gênero no Brasil), então escolaridade do pai pode ser mais forte pra renda familiar alta do que escolaridade da mãe.

pode ter mais registro de "mãe responsável" em famílias monoparentais (mãe solo), que tendem a ter renda per capita menor mesmo com escolaridade alta, puxando a média de "mãe com pós" pra baixo.

In [29]:
#Gráfico com matplot

---

## **Situação de conclusão do ensino médio**

In [30]:
mapa_conclusao = {
    1: 'Já concluí o Ensino Médio',
    2: 'Estou cursando e concluirei o Ensino Médio em 2025',
    3: 'Estou cursando e concluirei o Ensino Médio após 2025',
    4: 'Não concluí e não estou cursando o Ensino Médio'
}

df['situacao_conclusao'] = df['TP_ST_CONCLUSAO'].map(mapa_conclusao)

df['situacao_conclusao'].value_counts()

situacao_conclusao
Já concluí o Ensino Médio                               1888320
Estou cursando e concluirei o Ensino Médio em 2025      1811344
Estou cursando e concluirei o Ensino Médio após 2025      65958
Não concluí e não estou cursando o Ensino Médio           57500
Name: count, dtype: int64

In [31]:
tabela_st_conclusao_tipo_escola = (pd.crosstab(df['situacao_conclusao'], df['tipo_escola'], normalize='index') * 100).round(1)
tabela_st_conclusao_tipo_escola

tipo_escola,Não frequentou Ensino Médio,Pública + privada (com bolsa),Pública + privada (sem bolsa),Só privada (com bolsa),Só privada (sem bolsa),Só pública
situacao_conclusao,,,,,,
Estou cursando e concluirei o Ensino Médio após 2025,0.3,2.0,4.3,1.6,5.4,86.5
Estou cursando e concluirei o Ensino Médio em 2025,0.0,1.6,3.2,3.1,11.7,80.4
Já concluí o Ensino Médio,0.3,2.0,3.9,2.9,10.0,80.8
Não concluí e não estou cursando o Ensino Médio,8.9,1.5,4.0,0.6,2.1,82.9

O grupo que não concluiu e não está cursando o Ensino Médio apresenta uma característica própria: 8,9% desses candidatos relataram nunca ter frequentado o Ensino Médio, uma proporção muito acima das demais categorias (0,0% a 0,3%), o que sugere que parte desse grupo é composta por pessoas fora do sistema escolar regular, não apenas por quem interrompeu os estudos.

---

## **Comparações de renda dos candidatos**

In [32]:
#Inicialmente vamos separar categoria de renda dos participantes
#Vou analisar se posso explorar mais bem essa parte | OBS: Apliquei esse mapa_renda junto com internet, não sei vai ser mais util manter ele aqui
mapa_renda = {
    'A': 'Nenhuma renda',
    'B': 'Até R$ 1.518,00',
    'C': 'R$ 1.518,01 a R$ 2.277,00',
    'D': 'R$ 2.277,01 a R$ 3.036,00',
    'E': 'R$ 3.036,01 a R$ 3.795,00',
    'F': 'R$ 3.795,01 a R$ 4.554,00',
    'G': 'R$ 4.554,01 a R$ 6.072,00',
    'H': 'R$ 6.072,01 a R$ 7.590,00',
    'I': 'R$ 7.590,01 a R$ 9.108,00',
    'J': 'R$ 9.108,01 a R$ 10.626,00',
    'K': 'R$ 10.626,01 a R$ 12.144,00',
    'L': 'R$ 12.144,01 a R$ 13.662,00',
    'M': 'R$ 13.662,01 a R$ 15.180,00',
    'N': 'R$ 15.180,01 a R$ 18.216,00',
    'O': 'R$ 18.216,01 a R$ 22.770,00',
    'P': 'R$ 22.770,01 a R$ 30.360,00',
    'Q': 'Acima de R$ 30.360,00'
}

df['renda_familiar'] = df['Q007'].map(mapa_renda)

df['renda_familiar'].value_counts()

renda_familiar
Até R$ 1.518,00                1367120
R$ 1.518,01 a R$ 2.277,00       737000
Nenhuma renda                   389424
R$ 2.277,01 a R$ 3.036,00       357214
R$ 4.554,01 a R$ 6.072,00       198559
R$ 3.795,01 a R$ 4.554,00       179097
R$ 3.036,01 a R$ 3.795,00       161120
R$ 6.072,01 a R$ 7.590,00        97335
R$ 7.590,01 a R$ 9.108,00        73027
R$ 9.108,01 a R$ 10.626,00       55184
R$ 10.626,01 a R$ 12.144,00      44607
Acima de R$ 30.360,00            31716
R$ 13.662,01 a R$ 15.180,00      29426
R$ 15.180,01 a R$ 18.216,00      28644
R$ 18.216,01 a R$ 22.770,00      28485
R$ 22.770,01 a R$ 30.360,00      26028
R$ 12.144,01 a R$ 13.662,00      19136
Name: count, dtype: int64

In [33]:
#Organizar a renda de ordem crescer para não ficar com valores maior e menor 
# Verificar o que pode ser explorado com esse assunto
ordem_renda = list(mapa_renda.values())

ordem_escola = [
    'Só pública',
    'Pública + privada (sem bolsa)',
    'Pública + privada (com bolsa)',
    'Só privada (sem bolsa)',
    'Só privada (com bolsa)'
]

df_escola = df[df['Q023'] != 'F']

tabela_renda_escola = (
    pd.crosstab(
        df_escola['tipo_escola'],
        df_escola['renda_familiar'],
        normalize='index'
    ) * 100
).round(1)

# Utilizei reindex para organizar a faixa do tipo de rede escolar
tabela_renda_escola = tabela_renda_escola.reindex(index=ordem_escola, columns=ordem_renda)

tabela_renda_escola

renda_familiar,Nenhuma renda,"Até R$ 1.518,00","R$ 1.518,01 a R$ 2.277,00","R$ 2.277,01 a R$ 3.036,00","R$ 3.036,01 a R$ 3.795,00","R$ 3.795,01 a R$ 4.554,00","R$ 4.554,01 a R$ 6.072,00","R$ 6.072,01 a R$ 7.590,00","R$ 7.590,01 a R$ 9.108,00","R$ 9.108,01 a R$ 10.626,00","R$ 10.626,01 a R$ 12.144,00","R$ 12.144,01 a R$ 13.662,00","R$ 13.662,01 a R$ 15.180,00","R$ 15.180,01 a R$ 18.216,00","R$ 18.216,01 a R$ 22.770,00","R$ 22.770,01 a R$ 30.360,00","Acima de R$ 30.360,00"
tipo_escola,,,,,,,,,,,,,,,,,
Só pública,11.9,41.0,20.8,9.3,3.9,4.1,3.9,1.7,1.1,0.7,0.5,0.2,0.3,0.2,0.2,0.1,0.1
Pública + privada (sem bolsa),5.6,23.3,19.0,11.6,5.8,7.1,8.7,4.5,3.5,2.7,2.2,0.9,1.3,1.1,1.1,0.9,0.8
Pública + privada (com bolsa),6.7,30.1,22.4,12.1,5.5,6.3,6.7,3.1,2.1,1.5,1.0,0.4,0.5,0.5,0.3,0.3,0.3
Só privada (sem bolsa),1.5,6.0,7.7,7.5,5.0,7.3,11.6,7.4,6.7,6.3,5.5,2.5,4.3,4.4,4.9,4.9,6.5
Só privada (com bolsa),2.9,16.8,16.7,12.0,6.8,8.8,11.2,5.8,4.6,3.4,2.8,1.2,1.7,1.6,1.5,1.2,1.0

Entre os candidatos que estudaram somente em escola pública, há maior concentração de menor renda, com destaque para até R$1.518,00 (41,0%), e de R$1.518,01 a R$2.227,00 (20,8%). 11,9% declararam que não possui renda familiar.

Já entre os candidatos que estudaram sometne em escola privada sem bolsa, a distruibuição de renda varia entre faixas intermediárias e altas. De R$4.554,01 a R$ 6.072,00 representando 11,6%, enquanto 6,5% estão acima de R$ 30.360,00.

Os candidatos de escola privada com bolsa apresentando um perfil intermediário, com concetração nas faixas de R$1.518,00 representando 16,8%, de R$1.581,01 a 2,227,00 representando 16,7% e de R$ 4.554,01 a R$ 6.072,00 representando (11,2%).

---

## **Diferença entre escolas públicas e privadas durante a pandemia**

In [34]:
# Antes de começar, temos que enxergar as diferenças antes e durante a pandemia

mapa_escola_2019 = {
    1: 'Não informado',
    2: 'Pública',
    3: 'Privada'
}

df_2019['tipo_escola'] = df_2019['TP_ESCOLA'].map(mapa_escola_2019)

df_2019_notas = df_2019.dropna(subset=cols_desempenho[1:]).copy()

df_2019_notas['nota_media'] = (
    df_2019_notas[cols_desempenho[1:]].mean(axis=1)
)

In [35]:
media_2019 = (
    df_2019_notas.groupby('tipo_escola')['nota_media']
    .mean()
    .round(1)
)

gap_2019 = round(
    media_2019['Privada'] - media_2019['Pública'],
    1
)

comparacao_anual_2019 = pd.DataFrame({
    'Ano': [2019],
    'Pública': [media_2019['Pública']],
    'Privada': [media_2019['Privada']],
    'Não informado': [media_2019['Não informado']],
    'Diferença de Privada para Pública': [gap_2019]
})

comparacao_anual_2019

    Ano  Pública  Privada  Não informado  Diferença de Privada para Pública
0  2019    515.3    619.9          534.1                              104.6

---

## O Perfil da Abstenção

In [36]:
tabela_faltosos = pd.DataFrame({
    'Quantidade': [
        (df_resultados['TP_PRESENCA_CH'] == 0).sum(),
        (df_resultados['TP_PRESENCA_CN'] == 0).sum()
    ]
}, index=['1º dia', '2º dia'])

tabela_faltosos['Percentual (%)'] = (tabela_faltosos['Quantidade'] / len(df_resultados) * 100).round(1)

tabela_faltosos

        Quantidade  Percentual (%)
1º dia     1348087            28.0
2º dia     1548487            32.2

In [37]:
"""
Situação dos candidatos nos dois dias de prova

Além da abstenção em cada dia, analisamos o comportamento dos candidatos ao longo das duas aplicações, 
identificando aqueles que compareceram aos dois dias, faltaram aos dois dias ou compareceram somente a um deles.
"""

dia1 = df_resultados['TP_PRESENCA_CH']
dia2 = df_resultados['TP_PRESENCA_CN']

df_resultados['situacao_dias'] = 'Outros'

df_resultados.loc[(dia1 == 1) & (dia2 == 1), 'situacao_dias'] = 'Compareceu nos dois dias'
df_resultados.loc[(dia1 == 0) & (dia2 == 0), 'situacao_dias'] = 'Faltou nos dois dias'
df_resultados.loc[(dia1 == 1) & (dia2 == 0), 'situacao_dias'] = 'Compareceu somente no 1º dia'
df_resultados.loc[(dia1 == 0) & (dia2 == 1), 'situacao_dias'] = 'Compareceu somente no 2º dia'

In [38]:
tabela_situacao = df_resultados['situacao_dias'].value_counts().to_frame('Quantidade')

tabela_situacao['Percentual (%)'] = (tabela_situacao['Quantidade'] / len(df_resultados) * 100).round(1)

tabela_situacao

                              Quantidade  Percentual (%)
situacao_dias
Compareceu nos dois dias         3244348            67.4
Faltou nos dois dias             1332913            27.7
Compareceu somente no 1º dia      211292             4.4
Compareceu somente no 2º dia       15146             0.3
Outros                              7073             0.1

Considerando os registros disponíveis na base pública de resultados do ENEM 2025, no primeiro dia, 1.348.087 candidatos (28,0%) faltaram à prova, enquanto no segundo dia esse número aumentou para 1.548.487 candidatos (32,2%). Isso representa um aumento de 200.400 faltosos, ou 4,2 pontos percentuais.

Além disso, 211.292 candidatos (4,4%) compareceram ao primeiro dia, mas não retornaram para o segundo, enquanto apenas 15.146 (0,3%) compareceram somente ao segundo dia.

### Abstenção por Município/UF

Para identificar diferenças geográficas na abstenção do ENEM 2025, analisamos o percentual de faltosos 
em cada Unidade Federativa e Município no primeiro e no segundo dia de aplicação.

In [39]:


faltas_dia1_uf = pd.crosstab(df_resultados['SG_UF_PROVA'], df_resultados['TP_PRESENCA_CH'], normalize='index') * 100
faltas_dia2_uf = pd.crosstab(df_resultados['SG_UF_PROVA'], df_resultados['TP_PRESENCA_CN'], normalize='index') * 100

abstencao_uf = pd.DataFrame({
    '1º dia (%)': faltas_dia1_uf[0],
    '2º dia (%)': faltas_dia2_uf[0]
}).round(1)

abstencao_uf

             1º dia (%)  2º dia (%)
SG_UF_PROVA
AC                 34.3        38.9
AL                 26.4        30.1
AM                 40.7        45.8
AP                 30.7        35.5
BA                 29.2        33.0
CE                 21.5        24.6
DF                 26.8        31.3
ES                 29.0        34.0
GO                 28.7        33.7
MA                 27.7        31.7
MG                 29.6        33.4
MS                 29.1        34.1
MT                 35.7        40.8
PA                 29.8        34.4
PB                 25.5        28.6
PE                 25.4        29.1
PI                 25.6        28.3
PR                 27.1        32.3
RJ                 28.3        32.4
RN                 24.1        27.4
RO                 32.3        37.0
RR                 36.1        41.6
RS                 28.9        34.6
SC                 27.7        33.6
SE                 23.4        27.1
SP                 27.4        31.5
TO                 29.1        34.0

In [40]:
faltosos_municipio = pd.DataFrame({
    'Faltosos 1º dia': df_resultados[df_resultados['TP_PRESENCA_CH'] == 0].groupby(['NO_MUNICIPIO_PROVA', 'SG_UF_PROVA']).size(),
    'Faltosos 2º dia': df_resultados[df_resultados['TP_PRESENCA_CN'] == 0].groupby(['NO_MUNICIPIO_PROVA', 'SG_UF_PROVA']).size()
}).fillna(0).astype(int).reset_index()

maior_faltosos_municipio = (
    faltosos_municipio
    .sort_values('Faltosos 2º dia', ascending=False)
    .head(10)
)

maior_faltosos_municipio

     NO_MUNICIPIO_PROVA SG_UF_PROVA  Faltosos 1º dia  Faltosos 2º dia
1610          São Paulo          SP            51171            59092
1383     Rio de Janeiro          RJ            35752            41095
949              Manaus          AM            26636            30159
1404           Salvador          BA            25782            29275
260            Brasília          DF            22198            25955
215               Belém          PA            21109            24331
603           Fortaleza          CE            19914            23007
212      Belo Horizonte          MG            20405            22831
1593           São Luís          MA            15502            17720
1345             Recife          PE            13831            15840

Entre os municípios de aplicação com maior quantidade de faltosos, São Paulo (SP) apresentou os maiores valores nos dois dias, 
passando de 51.171 faltosos no primeiro dia para 59.092 no segundo. Em seguida aparece o Rio de Janeiro (RJ), que passou de 35.752 
para 41.095 faltosos.

O aumento também pode ser observado nos demais municípios da tabela. Manaus (AM), por exemplo, passou de 26.636 para 30.159 faltosos, enquanto Salvador (BA) passou de 25.782 para 29.275.

Por se tratar de valores absolutos, esses números devem ser considerados juntamente com a quantidade total de candidatos de cada município. Portanto, uma maior quantidade de faltosos não significa necessariamente uma maior taxa de abstenção.

In [41]:
menor_faltosos_municipio = (
    faltosos_municipio
    .sort_values('Faltosos 2º dia', ascending=True)
    .head(10)
)

menor_faltosos_municipio

       NO_MUNICIPIO_PROVA SG_UF_PROVA  Faltosos 1º dia  Faltosos 2º dia
587       Fernando Falcão          MA               14               15
588   Fernando de Noronha          PE               16               20
1440  Santa Rosa do Purus          AC               23               28
51                Amajari          RR               33               39
264    Brejinho de Nazaré          TO               32               39
971        Marcos Parente          PI               37               42
95               Araguanã          TO               42               47
184        Barra do Turvo          SP               40               49
1248     Pinheiro Machado          RS               44               52
134        Arroio do Meio          RS               45               55

Entre os municípios de aplicação com menor quantidade de faltosos, Fernando Falcão (MA) apresentou os menores valores, com 14 faltosos no primeiro dia e 15 no segundo. Fernando de Noronha (PE) aparece em seguida, passando de 16 para 20 faltosos, enquanto Santa Rosa do Purus (AC) passou de 23 para 28.

O aumento das faltas no segundo dia também ocorreu nos demais municípios da tabela. Amajari (RR) passou de 33 para 39 faltosos, Brejinho de Nazaré (TO) de 32 para 39 e Arroio do Meio (RS) de 45 para 55.

---

## Perfil etário dos candidatos

Nesta análise, buscamos identificar como os candidatos do ENEM 2025 estão distribuídos entre as diferentes faixas etárias, permitindo observar quais grupos possuem maior participação no exame.

In [42]:
df['TP_FAIXA_ETARIA'].value_counts().sort_index()

TP_FAIXA_ETARIA
1       11736
2      610363
3     1141912
4      483303
5      271801
6      178368
7      133343
8      104839
9       87249
10      74998
11     253931
12     150564
13     113921
14      84093
15      54700
16      34007
17      19343
18       9143
19       3834
20       1674
Name: count, dtype: int64

In [43]:
mapa_faixa_etaria = {
    1: 'Menor de 17 anos',
    2: '17 anos',
    3: '18 anos',
    4: '19 anos',
    5: '20 anos',
    6: '21 anos',
    7: '22 anos',
    8: '23 anos',
    9: '24 anos',
    10: '25 anos',
    11: 'Entre 26 e 30 anos',
    12: 'Entre 31 e 35 anos',
    13: 'Entre 36 e 40 anos',
    14: 'Entre 41 e 45 anos',
    15: 'Entre 46 e 50 anos',
    16: 'Entre 51 e 55 anos',
    17: 'Entre 56 e 60 anos',
    18: 'Entre 61 e 65 anos',
    19: 'Entre 66 e 70 anos',
    20: 'Maior de 70 anos'
}

df['faixa_etaria'] = df['TP_FAIXA_ETARIA'].map(mapa_faixa_etaria)

ordem_faixa_etaria = list(mapa_faixa_etaria.values())

In [44]:
tabela_faixa_etaria = df['faixa_etaria'].value_counts().reindex(ordem_faixa_etaria).to_frame('Quantidade')

tabela_faixa_etaria['Percentual (%)'] = (
    tabela_faixa_etaria['Quantidade'] / len(df) * 100
).round(1)

tabela_faixa_etaria

                    Quantidade  Percentual (%)
faixa_etaria
Menor de 17 anos         11736             0.3
17 anos                 610363            16.0
18 anos                1141912            29.9
19 anos                 483303            12.6
20 anos                 271801             7.1
21 anos                 178368             4.7
22 anos                 133343             3.5
23 anos                 104839             2.7
24 anos                  87249             2.3
25 anos                  74998             2.0
Entre 26 e 30 anos      253931             6.6
Entre 31 e 35 anos      150564             3.9
Entre 36 e 40 anos      113921             3.0
Entre 41 e 45 anos       84093             2.2
Entre 46 e 50 anos       54700             1.4
Entre 51 e 55 anos       34007             0.9
Entre 56 e 60 anos       19343             0.5
Entre 61 e 65 anos        9143             0.2
Entre 66 e 70 anos        3834             0.1
Maior de 70 anos          1674             0.0

A maior concentração de candidatos do ENEM 2025 está nas faixas etárias mais jovens. Os candidatos de 18 anos representam o maior grupo da base analisada, com 1.141.912 registros (29,9%), seguidos pelos candidatos de 17 anos, com 610.363 (16,0%), e de 19 anos, com 483.303 (12,6%).
Também se observa uma participação de candidatos em faixas etárias mais elevadas. O grupo entre 26 e 30 anos, por exemplo, representa 6,6% da base, enquanto candidatos entre 31 e 35 anos correspondem a 3,9%.

In [45]:
tabela_idade_conclusao = (
    pd.crosstab(
        df['faixa_etaria'],
        df['situacao_conclusao'],
        normalize='index'
    ) * 100
).round(1)

tabela_idade_conclusao = tabela_idade_conclusao.reindex(ordem_faixa_etaria)

tabela_idade_conclusao

situacao_conclusao,Estou cursando e concluirei o Ensino Médio após 2025,Estou cursando e concluirei o Ensino Médio em 2025,Já concluí o Ensino Médio,Não concluí e não estou cursando o Ensino Médio
faixa_etaria,,,,
Menor de 17 anos,0.0,91.6,8.4,0.0
17 anos,0.0,99.6,0.4,0.0
18 anos,3.7,82.3,13.6,0.4
19 anos,2.2,31.0,65.8,1.0
20 anos,1.2,14.8,82.6,1.4
21 anos,0.8,7.8,89.8,1.6
22 anos,0.7,5.4,92.1,1.7
23 anos,0.7,4.6,92.8,1.9
24 anos,0.7,4.1,93.0,2.2
25 anos,0.7,3.8,93.0,2.4
Entre 26 e 30 anos,0.6,3.3,92.6,3.5
Entre 31 e 35 anos,0.8,4.1,90.2,4.9
Entre 36 e 40 anos,0.9,4.6,89.5,5.0
Entre 41 e 45 anos,0.8,4.5,89.7,5.0
Entre 46 e 50 anos,1.0,5.0,88.3,5.7
Entre 51 e 55 anos,1.0,5.7,86.6,6.6
Entre 56 e 60 anos,1.2,6.4,85.8,6.7
Entre 61 e 65 anos,0.9,6.2,86.4,6.5
Entre 66 e 70 anos,1.1,6.4,85.9,6.6
Maior de 70 anos,1.3,6.3,84.8,7.6

Entre os candidatos de 17 anos, 99,6% estão cursando e devem concluir o Ensino Médio em 2025.
Aos 18 anos, esse grupo ainda representa a maioria, com 82,3%, enquanto 13,6% já concluíram o Ensino Médio. Aos 19 anos ocorre uma mudança significativa: 65,8% já concluíram, enquanto 31,0% ainda estão cursando e devem concluir em 2025.
A partir dos 20 anos, a maioria dos candidatos já concluiu o Ensino Médio. Esse percentual corresponde a 82,6% aos 20 anos e ultrapassa 90% em diversas faixas seguintes.

In [46]:
#Gabriel, preciso verificar contigo pois os dados de presença e dados de raça são dados distintos,
#Não possuem uma chave que permia ligar com segurança o mesmo canditato.
#Não vou citar quem faltou nas provas em relação a raças, pois não existe dados separado por raça que faltaram
# Imaginei em coletar do CSV do PARTICIPANTES_2025 mas vaimostra todos Inscritos e não faltosos.